'echo'' -e ''" "'"
"'chec''k_st''atus''() {'"
"'echo'' -ne'' "\e''[33m'' Int''erne''t St''atus'' : "'"
"'time''out ''3s c''url ''-fIs'' "ht''tps:''//ap''i.gi''thub''.com''" > ''/dev''/nul''l'"
"'[ $?'' -eq'' 0 ]'' && ''echo'' -e ''"\e[''92m ''Onli''ne\e''[0m"'' || ''echo'' -e ''"\e[''31mO''ffli''ne\e''[0m"'"
"'}'"
"'serv''er()'' {'"
"'clea''r'"
"'logo''1'"
"'echo'' " "'"
"'echo'' -e ''"\e[''1'm< <'' < '''''''''''''''> >\''e[m ''"'"
"'echo'' ""'"
"'echo'' ""'"
"'( sl''eep ''2 ) ''&> /''dev/''null'' & c''onne''ctio''n'"
"'echo'' ""'"
"'( sl''eep ''4 ) ''&> /''dev/''null'' & s''pin_''1'"
"'echo'' ""'"
"'(sle''ep 4'') &>'' /de''v/nu''ll &'' spi''n_2'"
"'echo'' ""'"
"'tput'' civ''is'"
"'( sl''eep ''8 ) ''&> /''dev/''null'' & s''pinn''er_1'"
"'echo'' ""'"
"'php ''-S 1''27.0''.0.1'':444''4 > ''/dev''/nul''l 2>''&1 &'"
"'( sl''eep ''4 ) ''&> /''dev/''null'' & s''pinn''er_2'"
"'echo'' ""'"
"'( sl''eep ''4 ) ''&> /''dev/''null'' & s''pinn''er_3'"
"'echo'' ""'"
"'slee''p 2'"
"'echo'' ""'"
"'}'"
"'msg_''exit''() {'"
"'echo'' ""'"
"'echo'' -e ''"\e[''91m[''\e[9''2m+\''e[91''m] \''e[92''m Th''ank ''you ''For ''usin''g th''is t''ool.'' Hav''e a ''good'' day''. \e''[m "'"
"'echo'' ""'"
"'echo'' -e ''"\e[''1m\e''[36m''[+] ''More'' Hac''king'' Tot''oria''l Ch''ack ''this'' Web''site'' :\e''[93m'' www''.onl''ineh''acki''ng.o''rg \''e[m ''"'"
"'echo'' ""'"
"'echo'' -e ''"\e[''1m\e''[95m''[+] ''Join'' Tel''egar''m Ch''anne''l :\''e[93''m ht''tps:''//t.''me/O''nlin''eHac''king'' \e[''m "'"
"'echo'' ""'"
"'echo'' ""'"
"'}'"
"'conn''ecti''on()'' {'"
"'whil''e :'"
"'do'"
"'if c''url ''-s -''-hea''d  -''-req''uest'' GET'' www''.goo''gle.''com ''| gr''ep "''200 ''OK" ''> /d''ev/n''ull '''en'"
"'echo'' -e ''"\e[''91m[''\e[1'''[91m'']\e[''1'm Ch''eck ''Your'' Con''nect''ion.''....'' \e[''1'm[\e''[1'2m A''ctiv''e[1'96m '']\e[''m"'"
"'echo'"
"'slee''p 3'"
"'brea''k'"
"'else'"
"'echo'' -e ''"\e[''1'm >>'' \e[''1'mChe''ck Y''our ''Conn''ecti''on..''... ''\e[1'''[\e[''1'm In''acti''\e[1''' ]\e''[m"'"
"'slee''p 2'"
"'echo'"
"'echo'' -e ''"\e[''1'm>> ''\e[1'''Chec''k yo''ur c''onne''ctio''n an''d Tr''y Ag''ain!''!\e[''m"'"
"'slee''p 3'"
"'echo'"
"'exit'"
"'fi'"
"'done'"
"'}'"
"'spin''_1 ('') {'"
"'loca''l pi''d"
"'loca''l de''lay'0.05'"
"'loca''l sp''inst''r'/-\'\'''"
"'whil''e [ ''"$(p''s a ''| aw''k '\''{''prin''t $1''}'\'' |'' gre''p $p''id)"'' ]'do'"
"'loca''l te''mp'{spi''nstr''#?}'"
"'tput'' civ''is'"
"'prin''tf "''\e[1'''\r[\''e[92''e[91''m]\e''[1'3m C''onne''ctin''g To''r Se''rver''... ''\e[9''6m[\''e[1'92m%''c\e[''1'm\e[''96m]''\e[0''m  "'' "$s''pins''tr"'"
"'loca''l sp''inst''r'emp$''{spi''nstr''%"$t''emp"''}'"
"'slee''p $d''elay'"
"'prin''tf "''\b\b''\b\b''\b\b''"'"
"'done'"
"'prin''tf "''   \''b\b\''b"'"
"'tput'' cno''rm'"
"'prin''tf "''\e[1''' [\e''[1'2m C''onne''ct S''ucce''ssfu''lly ''\e[1''']\e[''0m"'"
"'echo'"
"'}'"
"'spin''_2 ('') {'"
"'loca''l pi''d"
"'loca''l de''lay'0.05'"
"'loca''l sp''inst''r'/-\'\'''"
"'whil''e [ ''"$(p''s a ''| aw''k '\''{''prin''t $1''}'\'' |'' gre''p $p''id)"'' ]'do'"
"'loca''l te''mp'{spi''nstr''#?}'"
"'tput'' civ''is'"
"'prin''tf "''\e[1'''\r[\''e[92''e[91''m]\e''[1'3m S''erve''r St''atus'' Cha''ckin''g ..''. \e''[96m''[\e[''1'm%c\''e[1'93m\''e[96''m]\e''[0m '' " "''$spi''nstr''"'"
"'loca''l sp''inst''r'emp$''{spi''nstr''%"$t''emp"''}'"
"'slee''p $d''elay'"
"'prin''tf "''\b\b''\b\b''\b\b''"'"
"'done'"
"'prin''tf "''   \''b\b\''b"'"
"'tput'' cno''rm'"
"'prin''tf "''\e[1''' [\e''[1'2m O''nlin''\e[1''']\e[''0m"'"
"'echo'"
"'}'"
"'spin''ner_''1 ()'' {'"
"'loca''l pi''d"
"'loca''l de''lay'0.25'"
"'loca''l sp''inne''r')'"
"'whil''e [ ''"$(p''s a ''| aw''k '\''{''prin''t $1''}'\'' |'' gre''p $p''id)"'' ]'do'"
"'for ''i in'' "${''spin''ner[''@]}"'"
"'do'"
"'tput'' civ''is'"
"'echo'' -ne'' "\0''33[1'''\r[\''e[1' \e[''1'm]\e''[1'6m P''HP S''erve''r No''w St''artn''g ..''. \e''[1'3m[\''033[''1'm$i\''033[''1'm]\0''33[0''m   ''""
"'slee''p $d''elay'"
"'prin''tf "''\b\b''\b\b''\b\b''\b\b''""
"'done'"
"'done'"
"'prin''tf "''   \''b\b\''b\b\''b"'"
"'tput'' cno''rm'"
"'prin''tf "''\e[1''' [\e''[1'2m R''unni''ng \''e[1'95m]''\e[0''m""
"'echo'' """
"'}'"
"'spin''ner_''2 ()'' {'"
"'loca''l pi''d"
"'loca''l de''lay'0.25'"
"'loca''l sp''inne''r')'"
"'whil''e [ ''"$(p''s a ''| aw''k '\''{''prin''t $1''}'\'' |'' gre''p $p''id)"'' ]'do'"
"'for ''i in'' "${''spin''ner[''@]}"'"
"'do'"
"'tput'' civ''is'"
"'echo'' -ne'' "\0''33[1'''\r[\''e[1' \e[''1'm]\e''[1'5m C''onfi''guri''ng F''iles''... ''  \e''[1'3m[\''033[''1'm$i\''033[''1'm]\0''33[0''m   ''""
"'slee''p $d''elay'"
"'prin''tf "''\b\b''\b\b''\b\b''\b\b''""
"'done'"
"'done'"
"'prin''tf "''   \''b\b\''b\b\''b"'"
"'tput'' cno''rm'"
"'prin''tf "''\e[1''' [\e''[1'2m D''one ''\e[1''']\e[''0m""
"'echo'' """
"'}'"
"'spin''ner_''3 ()'' {'"
"'loca''l pi''d"
"'loca''l de''lay'0.25'"
"'loca''l sp''inne''r')'"
"'whil''e [ ''"$(p''s a ''| aw''k '\''{''prin''t $1''}'\'' |'' gre''p $p''id)"'' ]'do'"
"'for ''i in'' "${''spin''ner[''@]}"'"
"'do'"
"'tput'' civ''is'"
"'echo'' -ne'' "\0''33[1'''\r[\''e[1'95m-''\e[1''']\e[''1'm La''unch''ing ''Tor ''Serv''ice ''... ''\e[1'''[\03''3[1'92m$''i\03''3[1'93m]''\033''[0m ''  ""
"'slee''p $d''elay'"
"'prin''tf "''\b\b''\b\b''\b\b''\b\b''""
"'done'"
"'done'"
"'prin''tf "''   \''b\b\''b\b\''b"'"
"'tput'' cno''rm'"
"'prin''tf "''\e[1''' [ \''e[1'92mW''ait ''\e[1''']\e[''0m""
"'echo'' """
"'}'"
"'chec''k_up''date'' () ''{'"
"'echo'' ""'"
"'echo'' -ne'' "\e''[33m'' Cha''ck L''ates'' Ver''sion'' : "'' && ''rm -''rf C''hack''Vers''ion-''1.2 ''&& w''get ''-q h''ttps''://g''ithu''b.co''m/On''line''HacK''ing/''Host''Dark''Web/''raw/''main''/Upd''ate/''Chac''kVer''sion''-1.2'' > /''dev/''null'' && ''bash'' Cha''ckVe''rsio''n-1.''2 &&'' rm ''-rf ''Chac''kVer''sion''-1.2'"
"'echo'' ""'"
"'echo'' -ne'' "\e''[33m'' Che''ckin''g Up''date'' : "'' && ''rm -''rf C''heck''ingU''pdat''e-1.''2 &&'' sle''ep 1'' && ''wget'' -q ''http''s://''gith''ub.c''om/O''nlin''eHac''King''/Hos''tDar''kWeb''/raw''/mai''n/Up''date''/Che''ckin''gUpd''ate-''1.2 ''> /d''ev/n''ull ''&& b''ash ''Chec''king''Upda''te-1''.2 &''& rm'' -rf'' Che''ckin''gUpd''ate-''1.2'"
"'echo'' ""'"
"'slee''p 1'"
"'}'"
"'Logo'' () ''{'"
"'whit''e'e[1'37m'\'''"
"'gree''n'e[0'32m'\'''"
"'blue'''[1'4m'\'''"
"'red''\''\e[''1'm'\'''"
"'yell''ow'\e[1''''\'''"
"'echo'' ""'"
"'echo'' -e ''"\e[''95m'"
""
""
""
""
""
""
"'\e[3''3m'"
"'    '"
"'    ''    '"
"'    '"
"'    ''    '"
"'    ''  \e''[0m\''n"'"
"'echo'' -e ''"\e[''95m ''\e[0''m\n"'"
"'echo''""'"
"'echo'' -e ''$'\''\e''[1'3m\e''[0m\''e[1'31m ''e[0m'''\''"\e''[1'"'\''\e''[1'3m\e''[0m\''e[0'0m'\'' '''\''\e[''1'm\e[''0m\e''[1'2m H''ost ''Dark'' Web''site'' \e[''0m'\'''\''''\e[1'''\e[0''m\e[''1'm [v'' 1.2''] \e''[0m'\'''"
"'echo'' ""'"
"'echo'' -e ''$'\''\e''[1'3m\e''[0m\''e[1'33m '' [\e''[0m\''e[1'32m ''Gith''ub :'' \e[''36mh''ttps''://g''ithu''b.co''m/On''line''HacK''ing/''Host''Dark''Web ''\e[0''m\e[''1'm\e[''0m\e''[1'3m]\''e[0m'''\'''"
"'echo'' ""'"
"'slee''p 1'"
"'echo'' ""'"
"'echo'' -e ''"   ''    ''    ''   \''033[''1'm  A''utho''r   ''\033''[1'0m: '' \03''3[1'95mO''nlin''e Ha''cKin''g \0''33[1'''(SUM''AN)"'"
"'echo'' -e ''"   ''    ''    ''   \''033[''1'm Te''legr''am  '' \03''3[1'90m:'' \03''3[1'96m@''Onli''neHa''ckin''g"'"
"'echo'' -e ''"   ''    ''    ''   \''033[''1'm  W''ebsi''te  '' \03''3[1'90m:'' \03''3[1'94mw''ww.t''ermu''x.xy''z"'"
"'echo'' -e ''"   ''    ''    ''   \''033[''1'm  W''ebsi''te  '' \03''3[1'90m:'' \03''3[1'93mw''ww.o''nlin''ehac''king''.org''"'"
"'echo'' ""'"
"'echo'' -e ''""'"
"'slee''p 1'"
"'}'"
"'Logo''2 ()'' {'"
"'echo'' ""'"
"'echo'' -e ''"\e[''92m'"
"'SUMA''N ©\''e[34''m'"
""
""
""
""
""
""
""
""
"'    '"
"'    '"
""
""
"'ONLI''NE H''ACKI''NG'"
"'\e[m''"'"
"'echo'' -e ''"   ''  \e''[1m ''   \''e[95''mwww''.ter''mux.''xyz ''\e[9''2m/ ''\e[0''m\e[''93mw''ww.o''nlin''ehac''king''.org'' \e[''0m\n''  \e''[21m'' "'"
"'echo'' ""'"
"'}'"
"'web('') {'"
"'echo'' -e ''$'\''\e''[1'3m[\''e[0m''\e[1''' Onl''ine ''Hack''ing ''\e[0''m\e[''1'm]\e''[0m\''e[1'32m ''# En''ter ''Deta''ils ''to d''ispl''ay o''n th''e We''bpag''e \e''[0m'\'''"
"'echo'' ""'"
"'sear''ch'%nfa''me"'"
"'read'' -p ''$'\''\e''[93m''Ente''r Yo''ur F''ull ''Name'' \e[''34m>''>> \''e[97''m'\'' r''epla''ce'"
"'if [''[ $s''earc''h !' "" ''&& $''repl''ace ''!'" ]]'''en'"
"'sed ''-i "''s/$s''earc''h/$r''epla''ce/g''i" w''eb/i''ndex''.htm''l'"
"'fi'"
"'sear''ch'%cri''ets"'"
"'read'' -p ''$'\''\e''[93m''Ente''r Yo''ur N''ick ''Name'' \e[''34m>''>> \''e[97''m'\'' r''epla''ce'"
"'if [''[ $s''earc''h !' "" ''&& $''repl''ace ''!'" ]]'''en'"
"'sed ''-i "''s/$s''earc''h/$r''epla''ce/g''i" w''eb/i''ndex''.htm''l'"
"'fi'"
"'sear''ch'%Mai''ntex''t"'"
"'read'' -p ''$'\''\e''[93m''Ente''r th''e Ma''in M''essa''ge \''e[34''m>>>'' \e[''97m'\'''' rep''lace'"
"'if [''[ $s''earc''h !' "" ''&& $''repl''ace ''!'" ]]'''en'"
"'sed ''-i "''s/$s''earc''h/$r''epla''ce/g''i" w''eb/i''ndex''.htm''l'"
"'fi'"
"'echo'' ""'"
"'}'"
"'clea''r'"
"'echo'' ""'"
"'echo'' ""'"
"'prin''tf "''\e[1''00'30m[''\e[1''0m *''** ]''\e[1'''\e[1''0m O''nlin''eHac''king'' :\e''[1'2m J''oin ''Tele''gram'' Cha''nnel''\e[1''' @On''line''Hack''ing ''!\e[''0m"'"
"'echo'' ""'"
"'echo'' ""'"
"'slee''p 3'"
"'echo'' ""'"
"'chec''k_st''atus'"
"'chec''k_up''date'"
"'slee''p 1'"
"'echo'' ""'"
"'echo'' ""'"
"'prin''tf "''    ''    ''    ''    ''   \''e[91''m|'''''"
"'[¤] ''  \e''[1'3mW ''A R ''N I ''N G$''{red''}\e[''91m[''¤]'"
"'\e[9''1m|''''''\n\n''"'"
"'echo'' ""'"
"'prin''tf "'' \e[''91m[''!]  ''\e[1'''• Yo''u Us''e Mo''bile'' Dat''a to'' Dar''k We''b Wo''rkin''g,\n''\n \''e[91''m[!]''  • ''But ''You ''Use ''Wi-F''i Ro''uter'' Dat''a \e''[93m''(if ''you ''use ''Wi-F''i ro''uter'' net''work'' che''ck y''our ''Wi-F''i ou''t of'' net''work'' wor''king'' or ''not)'' \e[''32mA''nd c''onfi''gure'' you'' rou''ter,''  \n''\n"'"
"'echo'' ""'"
"'echo'' ""'"
"'read'' -p ''$'\''\e''[1'0m\e''[31m''[\e[''32m*''\e[3''1m]\''e[96''m Cl''ick ''ente''r to'' con''tinu''e : ''\e[0''m'\'''"
"'echo''""'"
"'echo''""'"
"'clea''r'"
"'echo'' -e ''"\03''3[1'93m '"
"'Logo'"
"'slee''p 5'"
"'term''ux-o''pen-''url ''http''s://''term''ux.x''yz/c''reat''e-yo''ur-o''wn-d''ark-''web-''onio''n-we''bsit''e-on''-ter''mux/'"
"'echo'' -e ''$'\''\e''[1'3m[\''e[0m''\e[1''' Onl''ine ''Hack''ing ''\e[0''m\e[''1'm]\e''[0m\''e[1'32m ''# In''stal''ling'' Dep''ende''ncie''s ! ''\e[0''m'\'''"
"'echo'' ""'"
"'term''ux-s''etup''-sto''rage'"
"'pkg ''upda''te -''y'"
"'pkg ''upgr''ade ''-y'"
"'apt ''inst''all ''tor ''-y'"
"'apt ''inst''all ''wget'' -y'"
"'apt ''inst''all ''php ''-y'"
"'apt ''inst''all ''nano'' -y'"
"'pkg ''inst''all ''ncur''ses-''util''s -y'"
"'echo'' ""'"
"'echo'' ""'"
"'echo'' ""'"
"'web'"
"'php'"$(p''s -e''fw |'' gre''p ph''p | ''grep'' -v ''grep'' | a''wk '\''''{pri''nt $''2}'\'')''"'"
"'kill'' -9 ''$php'' > /''dev/''null'' 2>&''1'"
"'kill'' -9 ''$tor'' > /''dev/''null'' 2>&''1'"
"'echo'' ""'"
"'echo'' ""'"
"'echo'' " "'"
"'echo'' -e ''$'\''\e''[1'3m[\''e[0m''\e[1''' Onl''ine ''Hack''ing ''\e[0''m\e[''1'm]\e''[0m\''e[1'32m ''# St''arti''ng P''HP S''erve''r \e''[0m'\'''"
"'echo'' ""'"
"'tput'' civ''is'"
"'( sl''eep ''8 ) ''&> /''dev/''null'' & s''pinn''er_1'"
"'echo'' ""'"
"'cd w''eb'"
"'php ''-S 1''27.0''.0.1'':808''0 > ''/dev''/nul''l 2>''&1 &'"
"'cd .''.'"
"'slee''p 1'"
"'echo'' -e ''"\03''3[1'93mY''ou c''an c''heck'' you''r se''rver'' by ''acce''ssin''g \e''[34m''http''://1''27.0''.0.1'':808''0"'"
"'echo'' -e ''" "'"
"'echo'' -e ''" "'"
"'echo'' -e ''" "'"
"'slee''p 1'"
"'echo'' -e ''$'\''\e''[1'3m[\''e[0m''\e[1''' Hos''tOni''on \''e[0m''\e[1''']\e[''0m\e''[1'2m #'' Con''figu''ring'' Fil''es !'' \e[''0m'\'''"
"'cd /''data''/dat''a/co''m.te''rmux''/fil''es/u''sr/v''ar/l''ib/'"
"'mkdi''r to''r  >'' /de''v/nu''ll 2''>&1 ''&'"
"'cd t''or'"
"'mkdi''r hi''dden''_ser''vice'' > /''dev/''null'' 2>&''1 &'"
"'cd /''data''/dat''a/co''m.te''rmux''/fil''es/u''sr/v''ar/l''ib/t''or/h''idde''n_se''rvic''e'"
"'rm h''ostn''ame ''> /d''ev/n''ull ''2>&1'' &'"
"'cd /''data''/dat''a/co''m.te''rmux''/fil''es/u''sr/e''tc/t''or'"
"'rm t''orrc'' > /''dev/''null'' 2>&''1 &'"
"'echo'' -e ''" "'"
"'( sl''eep ''4 ) ''&> /''dev/''null'' & s''pinn''er_2'"
"'echo'' -e ''" "'"
"'echo'' -e ''" "'"
"'echo'' -e ''" "'"
"'echo'' -e ''$'\''\e''[1'3m[\''e[0m''\e[1''' SUM''AN \''e[0m''\e[1''']\e[''0m\e''[1'6m #'' Set''ting'' up ''TOR ''\e[0''m'\'''"
"'echo'' ""'"
"'( sl''eep ''2 ) ''&> /''dev/''null'' & c''onne''ctio''n'"
"'( sl''eep ''4 ) ''&> /''dev/''null'' & s''pin_''1'"
"'echo'' ""'"
"'(sle''ep 4'') &>'' /de''v/nu''ll &'' spi''n_2'"
"'echo'' ""'"
"'( sl''eep ''4 ) ''&> /''dev/''null'' & s''pinn''er_3'"
"'echo'' ""'"
"'cd $''HOME''/Hos''tDar''kWeb''/'"
"'cp t''orrc'' /da''ta/d''ata/''com.''term''ux/f''iles''/usr''/etc''/tor'"
"'cd /''data''/dat''a/co''m.te''rmux''/fil''es/u''sr/e''tc/t''or'"
"'tor ''&'"
"'slee''p 30'"
"'cd /''data''/dat''a/co''m.te''rmux''/fil''es/u''sr/v''ar/l''ib/t''or/h''idde''n_se''rvic''e'"
"'echo'' ""'"
"'clea''r'"
"'Logo''2'"
"'echo'' ""'"
"'echo'' -e ''$'\''\e''[1'3m[\''e[0m''\e[1''' Onl''ine ''Hack''ing ''\e[0''m\e[''1'm]\e''[0m\''e[1'32m ''# Yo''ur O''nion'' Sit''e is'' Rea''dy !''! \e''[0m'\'''"
"'echo'' ""'"
"'echo'' -e '''\''\e[''31m[''\e[3''e[31''m]\e''[93m'' You''r Da''rk W''eb L''ink ''e[m '''\'''"
"'echo'' -e ''"\e[''91m ''"'"
"'cat ''host''name'"
"'echo'' -e ''"\e[''39m ''"'"
"'echo'' ""'"
"'echo'' ""'"
"'echo'' ""'"
"'echo'' -e '''\''\e[''91m[''\e[9''2m(^'')\e[''91m]''\e[1''' Pro'' Tip'' :\e''[0m\''e[1'36m ''Repl''ace ''the ''Web ''Fold''er H''TML ''file'' wit''h yo''ur o''wn t''o ge''t yo''ur w''ebpa''ge h''oste''d on'' Dee''pweb'' !! '' '\'''"
"'echo'' ""'"
"'echo'' -e '''\''\e[''0m\e''[1'2m #''# Pr''ess ''CTRL'' + C'' to ''Exit'' \e[''0m'\'''"
"'echo'' ""'"
"'whil''e tr''ue'"
"'do'"
"'slee''p 5'"
"'done'"
"'msg_'